name: dealers_stock_managment
recipe: laravel
config:
  webroot: .
  php: '8.1'
  composer_version: '2.5.2'
  via: apache:2.4
  server: config/httpd.conf
  database: mysql:5.7
  vhosts: config/default.conf
  conf:
    php: conf/php.ini
services:
  phpmyadmin:
    type: phpmyadmin
